MyFirstMVC/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyFirstMVC.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
        
    }
}

MyFirstMVC/Controllers/PFolioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyFirstMVC.Controllers
{
    public class PFolioController : Controller
    {
        // GET: PFolio
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Education()
        {
            return View();
        }
        public ActionResult Soram()
        {
            return View();
        }
        public ActionResult Skills()
        {
            return View();
        }
        public ActionResult Experience()
        {
            return View();
        }
        public ActionResult Hobby()
        {
            return View();
        }
       
        public ActionResult Register()
        {
            return View();
        }
        public ActionResult BasicDetail()
        {
            return View();
        }
    }
}

MyFirstMVC/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

MyFirstMVC/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

MyFirstMVC/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

MyFirstMVC/Views/PFolio/BasicDetail.cshtml
@{
    ViewBag.Title = "BasicDetail";
}

<h2>BasicDetail</h2>

<div class="button">
    <button class="cbutton" onclick="Hobby()">Hobby</button>
    <button class="cbutton" onclick="Education()">Education</button>
    <button class="cbutton" onclick="Experience()">Experience</button>
    <button class="cbutton" onclick="Skills()">Skills</button>
</div>

MyFirstMVC/Views/PFolio/Education.cshtml
@{
    ViewBag.Title = "Education";
}

<h2>Education</h2>

<table style="border:solid 1px" class="para">
        <thead  >
            <tr>
                <th style="border: solid 1px; padding: 5px">Education </th>
                <th style="border: solid 1px; padding: 5px">School/Colleges</th>
                <th style="border: solid 1px; padding: 5px">Year of Passout</th>
             </tr>
        </thead>
        <tbody style="border:solid 1px">
            <tr>
                <td style="border: solid 1px; padding: 5px">10 Std</td>
                <td style="border: solid 1px; padding: 5px">Baldwin Boys High School</td>
                <td style="border: solid 1px; padding: 5px">2013</td>
            </tr>
            <tr>
                <td style="border:solid 1px;padding:5px">12 Std</td>
                <td style="border: solid 1px; padding: 5px">Manipur Public School</td>
                <td style="border: solid 1px; padding: 5px">2015</td>
            </tr>
            <tr>
                <td style="border: solid 1px; padding: 5px">Btech</td>
                <td style="border: solid 1px; padding: 5px">SVCET</td>
                <td style="border: solid 1px; padding: 5px">2020</td>
            </tr>
        </tbody>
</table>

MyFirstMVC/Views/PFolio/Experience.cshtml
@{
    ViewBag.Title = "Experience";
}
 
<h2 id="skill-title">Experience</h2>
<ul class="exp">
    <li>Experience of 1 year in frontend development</li>
    <li>Worked on building UI using Reactjs</li>
    <li>Used AntD , MaterialUI </li>
    <li>Reactstrap</li>
    <li>Redux</li>
</ul>

MyFirstMVC/Views/PFolio/Hobby.cshtml
@{
    ViewBag.Title = "Hobby";
}

<h2>Hobby</h2>
<h2 id="skill-title">My hobbies are:-</h2>
<ul class="hobby">
    <li>playing guitar</li>
    <li>gardening</li>
    <li>listening to music</li>
    <li>watching web series</li>
    <li>playing football</li>
</ul>

MyFirstMVC/Views/PFolio/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

MyFirstMVC/Views/PFolio/Register.cshtml
@{
    ViewBag.Title = "Register";
}

<h2>Register</h2>
<div class=" ">
    <form action="Register" method="post">
        <label>Name :</label><br/>
        <input type="text" name="name" class="form-name" /><br />
        <label>Education :</label><br />
        <input type="text" name="education" class="form-" /><br />
        <label>Skills :</label><br />
        <input type="text" name="skills" class="" /><br />
        <label>Experience :</label><br />
        <input type="text" name="experience" class="" /><br/>
        <label>Hobby :</label><br />
        <input type="text" name="hobby" class="" /><br/><br/>
        <input type="submit" name="submit" class="btn-success" />
    </form>
</div>

MyFirstMVC/Views/PFolio/Skills.cshtml
@{
    ViewBag.Title = "Skills";
}

<h2 id="skill-title">Skills</h2>
<ul class="skills">
    <li>html</li>
    <li>css</li>
    <li>javascript</li>
    <li>reactjs</li>
</ul>

MyFirstMVC/Views/PFolio/Soram.cshtml
@{
    ViewBag.Title = "Soram";
}
<br/>
<br/>
<p class="para">Hi my name is Soram Wanglen.<br/> I'm currently working as a software associate consultant at Gyansys Infotech.<br/> Currently
    I'm undergoing training in .NET MVC. <br/>
    Looking forward to completing the course.</p>

MyFirstMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
               
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Soram", "Soram", "PFolio")</li>
                    <li>@Html.ActionLink("Education", "Education", "PFolio")</li>
                    <li>@Html.ActionLink("Skills", "Skills", "PFolio")</li>
                    <li>@Html.ActionLink("Hobby", "Hobby", "PFolio")</li>
                    <li>@Html.ActionLink("Experience", "Experience", "PFolio")</li>
                    <li>@Html.ActionLink("Register", "Register", "PFolio")</li>
                    <li>@Html.ActionLink("BasicDetail", "BasicDetail", "PFolio")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
           
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>